### ISSUE TITLE
need to change korean

### ISSUE THREAD

**Issue by Youngjin-KimY** [mcognetta/mcognetta.github.io#6]
저는 도쿄공업대학(Tokyo Institute of Technology)의 [Okazaki 연구실](https://www.nlp.c.titech.ac.jp/)의 ***박사하정 학생하고*** 구글 지보드(Gboard)팀의 개발자 마르코입니다. 조지아텍에서 이산수학을 전공, 한국어를 부전공하였고 이후에 연세대학교의 [계산이론 연구실](https://toc.yonsei.ac.kr/)에서 컴퓨터 과학 석사학위를 ***수료***하였습니다.

1. 박사하정 학생하고 -> 박사과정 학생이고
2. 석사학위를 수료하였습니다. -> 석사학위를 완료하였습니다.("수료" uses to complete only coursework in Korea)

happy sunday

**Comment by mcognetta** [comment]
아 고맙습니다! 수정했습니다.

근데 궁금한 게 있는데, 제 웹사이트를 어떻게 발견하셨나요?
